// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUKAj8Av6thj7k8XEdQn_oEffdkiKBNeM',
    appId: '1:965082785730:web:c2270f82d95c9fa30a985b',
    messagingSenderId: '965082785730',
    projectId: 'fitjungapplication',
    authDomain: 'fitjungapplication.firebaseapp.com',
    storageBucket: 'fitjungapplication.appspot.com',
    measurementId: 'G-S3R91YTQ0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwAc6GtGsilfIL0BuWWmTo_Y8mmaoacZE',
    appId: '1:965082785730:android:143dee5b8e0967700a985b',
    messagingSenderId: '965082785730',
    projectId: 'fitjungapplication',
    storageBucket: 'fitjungapplication.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2y6Ofy4KO3TPQbPstUhTNPSd5xunr5Cw',
    appId: '1:965082785730:ios:311bf707c4f787470a985b',
    messagingSenderId: '965082785730',
    projectId: 'fitjungapplication',
    storageBucket: 'fitjungapplication.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2y6Ofy4KO3TPQbPstUhTNPSd5xunr5Cw',
    appId: '1:965082785730:ios:6d9c4fd5896c6d8d0a985b',
    messagingSenderId: '965082785730',
    projectId: 'fitjungapplication',
    storageBucket: 'fitjungapplication.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
